services:
  - type: web
    name: parbat-furniture
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic --noinput
    startCommand: gunicorn parbat_furniture.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.4
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: false
